SELECT
  PARSE_DATE('%d.%m.%Y', `Order Date`) AS order_date,
  PARSE_DATE('%d.%m.%Y', `Ship Date`) AS ship_date,
  `Order ID` AS order_id,
  `Customer ID` AS customer_id,
  `Customer Name` AS customer_name,
  Discount AS discount,
  Country AS country,
  Region AS region,
  State AS state,
  CAST(`Postal Code` AS STRING) AS postal_code,
  City AS city,
  Category AS product_category,
  `Sub-Category` AS product_sub_category,
  `Product ID` AS product_id,
  `Product Name` AS product_name,
  Profit AS profit,
  Quantity AS quantity,
  Sales AS sales,
  Segment AS buyer_segment,
  `Ship Mode` AS ship_mode,
FROM `fifth-glider-352817`.`super_shop_raw`.`orders_raw`